#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate the pinned console preset catalog without network access."""
import json
from pathlib import Path
root = Path(__file__).resolve().parents[1]
media = json.loads((root / 'model-tools/presets.json').read_text())
models = []
for name in ['mistral-7b-instruct-v0.3-q4-0', 'qwen3.5-9b-q4-0']:
    recipe = json.loads((root / 'model-tools/recipes' / (name + '.json')).read_text())
    source = recipe['source']
    models.append(dict(id=name+'.gguf', name=recipe['model']['name'], kind=0,
                       repository=source['repository'], revision=source['revision'],
                       files=[dict(source=source['file'], path='', size=source['bytes'], sha256=source['sha256'])]))
models += media
lines = ['// Generated by tools/generate-model-presets.py; SPDX-License-Identifier: GPL-3.0-or-later',
         '#pragma once', '#include <cstddef>', '#include <cstdint>',
         'namespace prospero_model_download {',
         'struct PresetFile { const char *source, *path, *sha256; std::uint64_t size; };',
         'struct Preset { const char *id, *name, *repository, *revision; int kind; std::uint64_t size; const PresetFile *files; std::size_t count; };']
quote = json.dumps
for i, model in enumerate(models):
    assert len(model['revision']) == 40
    lines.append(f'inline constexpr PresetFile preset_files_{i}[] = {{')
    for file in model['files']:
        assert len(file['sha256']) == 64 and all(c in '0123456789abcdef' for c in file['sha256'])
        for path in [file['source'], file['path']]:
            assert not path.startswith('/') and '..' not in path and '\\' not in path
        lines.append('    {' + ', '.join(quote(file[k]) for k in ['source', 'path', 'sha256']) + f", {file['size']}ULL" + '},')
    lines.append('};')
lines.append('inline constexpr Preset presets[] = {')
for i, model in enumerate(models):
    lines.append('    {' + ', '.join(quote(model[k]) for k in ['id', 'name', 'repository', 'revision']) +
                 f", {model['kind']}, {sum(f['size'] for f in model['files'])}ULL, preset_files_{i}, {len(model['files'])}" + '},')
lines += ['};', 'inline constexpr std::size_t preset_count = sizeof(presets) / sizeof(presets[0]);', '}']
(root / 'include/model_presets.hpp').write_text('\n'.join(lines) + '\n')
