# SPDX-License-Identifier: GPL-3.0-or-later
get_filename_component(PROS_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(PS5_SDK "${PROS_ROOT}/.deps/mihawk-vulkan-review/.deps/native/ps5-payload-sdk")
set(CMAKE_SYSTEM_NAME FreeBSD)
set(CMAKE_SYSTEM_VERSION 9)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_C_COMPILER clang-18)
set(CMAKE_CXX_COMPILER clang++-18)
set(CMAKE_C_COMPILER_TARGET x86_64-sie-ps5)
set(CMAKE_CXX_COMPILER_TARGET x86_64-sie-ps5)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(CMAKE_C_FLAGS_INIT "-isysroot ${PS5_SDK} -isystem ${PS5_SDK}/target/include -fvisibility-nodllstorageclass=default -fno-stack-protector -fno-plt -femulated-tls -ffunction-sections -fdata-sections")
set(CMAKE_CXX_FLAGS_INIT "-isystem ${PS5_SDK}/target/include/c++/v1 ${CMAKE_C_FLAGS_INIT} -stdlib=libc++ -fexceptions -fcxx-exceptions -frtti -I${PROS_ROOT}/build/llama-vulkan/include-shim")
